// Custom Worker entrypoint (wrangler.jsonc "main"): wraps the OpenNext
// fetch handler and adds the poller's scheduled + queue handlers — the
// documented @opennextjs/cloudflare pattern for non-fetch events.
// @ts-ignore — generated by `opennextjs-cloudflare build`, absent while the
// inner `next build` typechecks (the adapter wipes .open-next first).
import openNextHandlerModule from "../.open-next/worker.js";

const openNextHandler = openNextHandlerModule as ExportedHandler<CloudflareEnv>;
// Side effect: populates the connector registry (one line per vendor).
import "./connectors";
import { createDb } from "./db/client";
import type { CredentialEnv } from "./lib/credentials";
import { listOrgIds } from "./db/system";
import { dispatchDueConnectorWork } from "./poller/dispatch";
import { SYSTEM_ORG_ID, type PollMessage } from "./poller/messages";
import { processPollMessage } from "./poller/process";
import { retryDelaySeconds, RetryableConnectorError } from "./poller/run";
import { previousDay } from "./scoring";

// Matches the second entry in wrangler.jsonc "triggers".crons — the nightly
// score recompute (W1-F). The */5 tick keeps the W0-B heartbeat + purge.
const NIGHTLY_SCORE_CRON = "0 2 * * *";

export default {
  fetch: openNextHandler.fetch,

  // Cron Trigger (every 5 min): heartbeat + raw purge (W0-B/C), then W1-D
  // connector dispatch — one queue message per due connection (regular
  // polls when the vendor interval elapsed; the chunked backfill
  // chain-start once per new connection).
  async scheduled(controller, env) {
    if (controller.cron === NIGHTLY_SCORE_CRON) {
      // Nightly score recompute: one queue message per org, anchored at
      // yesterday UTC (the last fully-ingested day).
      const db = createDb(env);
      const day = previousDay(new Date().toISOString().slice(0, 10));
      for (const orgId of await listOrgIds(db)) {
        await env.POLL_QUEUE.send({
          kind: "score-recompute",
          orgId,
          day,
        } satisfies PollMessage);
      }
      return;
    }
    await env.POLL_QUEUE.send({
      kind: "noop-poll",
      orgId: SYSTEM_ORG_ID,
    } satisfies PollMessage);
    await env.POLL_QUEUE.send({ kind: "purge-raw" } satisfies PollMessage);
    const db = createDb(env);
    await dispatchDueConnectorWork(db, {
      send: async (message) => {
        await env.POLL_QUEUE.send(message);
      },
    });
  },

  async queue(batch, env) {
    const db = createDb(env);
    for (const message of batch.messages) {
      try {
        await processPollMessage(db, message.body, {
          credentialEnv: env as unknown as CredentialEnv,
          send: async (m, opts) => {
            await env.POLL_QUEUE.send(
              m,
              opts?.delaySeconds ? { delaySeconds: opts.delaySeconds } : undefined,
            );
          },
          attempt: message.attempts,
        });
        message.ack();
      } catch (error) {
        // Permanent connector failures are recorded on the run/connection
        // inside the handler and never reach here; what does is retryable:
        // vendor 429/5xx (with its own delay) or an unexpected crash
        // (default queue backoff). The consumer's max_retries (set
        // explicitly in wrangler.jsonc) bounds redelivery; always log —
        // a message dropped after its last retry must not vanish silently.
        console.error(
          `[queue] ${message.body.kind} attempt ${message.attempts} failed:`,
          error,
        );
        if (error instanceof RetryableConnectorError) {
          message.retry({
            delaySeconds: Math.max(
              error.delaySeconds,
              retryDelaySeconds(message.attempts),
            ),
          });
        } else {
          message.retry();
        }
      }
    }
  },
} satisfies ExportedHandler<CloudflareEnv, PollMessage>;
