// Custom Worker entrypoint (wrangler.jsonc "main"): wraps the OpenNext
// fetch handler and adds the poller's scheduled + queue handlers — the
// documented @opennextjs/cloudflare pattern for non-fetch events.
// @ts-ignore — generated by `opennextjs-cloudflare build`, absent while the
// inner `next build` typechecks (the adapter wipes .open-next first).
import openNextHandlerModule from "../.open-next/worker.js";

const openNextHandler = openNextHandlerModule as ExportedHandler<CloudflareEnv>;
import { createDb } from "./db/client";
import { SYSTEM_ORG_ID, type PollMessage } from "./poller/messages";
import { processPollMessage } from "./poller/process";

export default {
  fetch: openNextHandler.fetch,

  // Cron Trigger → one queue message per connection. W0-B has no
  // connections yet, so it enqueues the single no-op heartbeat poll.
  async scheduled(controller, env) {
    await env.POLL_QUEUE.send({
      kind: "noop-poll",
      orgId: SYSTEM_ORG_ID,
    } satisfies PollMessage);
  },

  async queue(batch, env) {
    const db = createDb(env);
    for (const message of batch.messages) {
      await processPollMessage(db, message.body);
      message.ack();
    }
  },
} satisfies ExportedHandler<CloudflareEnv, PollMessage>;
